---
# main.yml
- name: Include Homebrew Package List
  include_vars:
    file: homebrew.yml
    name: homebrew_installed_packages
  tags: always

- name: Tap cask-drivers
  homebrew_tap:
    name: homebrew/cask-drivers
    state: present
  tags: 
  - homebrew

- name: Get Login Items
  shell: osascript -e 'tell application "System Events" to get login items'
  register: login_items
  tags:
  - homebrew

- name: Disable Steam open on startup
  shell: osascript -e 'tell application "System Events" to delete login item "Steam"'
  register: terminal_theme
  when: '"Steam" is in login_items.stdout'
  changed_when: false
  tags: 
  - homebrew

- name: Disable battle-net open on startup
  shell: osascript -e 'tell application "System Events" to delete login item "Battle.net"'
  register: terminal_theme
  when: '"Battle.net" is in login_items.stdout'
  changed_when: false
  tags: 
  - homebrew

  - osx_defaults:
    domain: com.apple.Finder
    key: ShowStatusBar
    type: bool
    value: true
    state: present
  tags: settings  

- osx_defaults:
    domain: com.apple.Finder
    key: ShowTabBar
    type: bool
    value: true
    state: present
  tags: settings 

- import_role:
        name: geerlingguy.mas
  when: mas_installed_apps
  tags: mas

- osx_defaults:
    domain: com.apple.Finder
    key: ShowPathbar
    type: bool
    value: true
    state: present
  tags: settings

#defaults write ~/library/containers/com.apple.safari/data/library/preferences/com.apple.safari.plist

# - name: Sign in to 1Password
#   expect: 
#     command: op signin my.1password.com welchsteven@gmail.com "{{ op_secret }}"
#     responses:
#       (?i)password: "{{ op_password }}"
#   tags: op


# - name: Zoom settings
# - name: calendar settings
# - name: Slack Settings
# - mac settings
# - dock
# - power
# - desktops